[project]
name = "unfolding"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pymc>=5.16.2",
]

[tool.uv]
dev-dependencies = [
    "ipywidgets>=8.1.5",
    "jupyterlab>=4.2.5",
    "ruff>=0.6.5",
]
